config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: :show
  resources :events
  resources :invitations

  get '/my_events', to: 'events#my_index'

  root to: "home#index"
end

app/models/event.rb
class Event < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  has_many :invitations
  has_many :users, through: :invitations

  belongs_to :owner, class_name: 'User'
  
  def self.get_events_page(page)
    Event.order('start_date DESC')#.paginate(page: page, per_page: 5)
  end
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates :event_id, presence: true
  validates :user_email, presence: true, format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/ }#, uniqueness: true
  #validates_format_of :user_email,:with => Devise::email_regexp

  def self.create_invitations(invitation_event_id, user_emails)
    #invitation_event_id = params[:invitation][:event_id]
    #emails = user_emails
    #user_emails = params[:invitation][:user_emails]
    valid_invitations = []
    invalid_emails = []
    user_emails.split(", ").each do |email|
      if User.find_by_email(email)
        invitation = Invitation.new(event_id: invitation_event_id)
        invitation.user = User.find_by_email(email)
        invitation.user_email = User.find_by_email(email).email
        if invitation.valid?
          valid_invitations << invitation
        end

      else
        invitation = Invitation.new(event_id: invitation_event_id)
        invitation.user_email = email
        if invitation.valid?
          valid_invitations << invitation
        else
          invalid_emails << email
        end
      end
    end

    if invalid_emails.empty?
      valid_invitations.each do |inv|
        inv.save
        UserMailer.event_email(inv).deliver
      end
    end
    invalid_emails
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader, :default_url => "/images/missing.png"
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :invitations
  has_many :events, through: :invitations

  has_many :own_events, class_name: 'Event', foreign_key: 'owner_id'

  # def own_events
  #   self.events
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!, except: [:invitation, :edit, :update]
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name, :email, :password, :avatar]
    devise_parameter_sanitizer.for(:account_update) << [:first_name, :last_name, :email, :password, :avatar]
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.get_events_page(params[:page])
  end

  def my_index
    @events = Event.get_events_page(params[:page])
  end

  def show
    @event_invitations = @event.invitations.where(accepted: true)
    #puts @event_invitations
  end

  def new
    @event = Event.new
    @event.owner = User.find(params[:owner_id])
  end

  def edit
  end

  def create
    #@event_user = params[:event][:user_id]
    @event = Event.new(event_params)
    @event.owner = current_user
    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: 'Event was successfully destroyed.'
  end

  private
  def set_event
    begin
      @event = Event.friendly.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to events_path, notice: "We did not find that Event."
    end
  end

  def event_params
    params.require(:event).permit(:name, :description, :start_date, :end_date, :location)
  end
end

# The require method ensures that a specific parameter is present, and if it's not provided, 
# the require method throws an error. It returns an instance of ActionController::Parameters for the key passed into require.
# The permit method returns a copy of the parameters object, returning only the permitted keys and values. 
# When creating a new ActiveRecord model, only the permitted attributes are passed into the model.

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events = Event.get_events_page(params[:page])
    @future_events = Event.all.where(['start_date > ?', Time.now])
    @past_events = Event.all.where(['start_date <= ?', Time.now])
    @user = current_user
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def index
  end

  def show
  end

  def new
    @invitation = Invitation.new
    @invitation.event = Event.find(params[:event_id])
    @user_emails = params[:user_emails]
  end

  def edit
    @invitation = Invitation.find(params[:id])
  end

  def create
    @user_emails = params[:invitation][:user_emails]
    invalid_emails = Invitation.create_invitations(params[:invitation][:event_id], params[:invitation][:user_emails])
    if invalid_emails.empty?
      redirect_to event_path(params[:invitation][:event_id]), notice: 'Invitation was successfully send to ' + @user_emails + '.'
    else
      redirect_to new_invitation_path(event_id: params[:invitation][:event_id], user_emails: @user_emails), alert: 'I did not send out the invitations because these formats are invalid: ' + invalid_emails.join(', ') + '.'
    end

    # user_emails = params[:invitation][:user_emails]
    # user_emails.split(", ").each do |email|
    #   if User.find_by_email(email)
    #     @invitation = Invitation.new(event_id: params[:invitation][:event_id])
    #     @invitation.user = User.find_by_email(email)
    #     @invitation.user_email = User.find_by_email(email).email
    #     if @invitation.save
    #       UserMailer.event_email(@invitation).deliver
    #     end

    #   else
    #     @invitation = Invitation.new(event_id: params[:invitation][:event_id])
    #     #@invitation.user = User.new
    #     @invitation.user_email = email
    #     if @invitation.save
    #       UserMailer.event_email(@invitation).deliver
    #     end

    #     # respond_to do |format|
    #     #   if @invitation.save
    #     #     UserMailer.event_email(@invitation, @receivers).deliver
    #     #     redirect_to @invitation, notice: 'Invitation was successfully send.'
    #     #   else
    #     #     render :new
    #     #   end
    #     # end
    #   end
    # end
  end

  def update
    @invitation = Invitation.find(params[:id])
    if @invitation.update_attribute(:accepted, true)
      redirect_to edit_invitation_path, notice: 'Invitation was accepted.'
    else
      render :edit
    end
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_all_table.html.haml
/= will_paginate @events
%table
  %thead
    %tr
      %th Name
      %th Start date
      %th End date
      %th Location
      %th Description
      %th
  %tbody
    - @events.each do |event|
      %tr
        %td= event.name
        %td= event.start_date#.strftime("%d/%m/%Y %H:%M")
        %td= event.end_date#.strftime("%d/%m/%Y %H:%M")
        %td= event.location
        %td= event.description
        - if user_signed_in?
          %td
            = link_to 'S', event, method: :get
          - if event.owner == current_user
            %td
              = link_to 'E', "/events/#{event.id}/edit"
            %td
              = link_to 'D', event, method: :delete, data: { confirm: 'Are you sure?' }
/= will_paginate @events
%br
.inv-butt
  = link_to 'Create a new event', new_event_path
%br
  = link_to "Back", :back

app/views/events/_f_p_table.html.haml
%h3 Events waiting for you
/= will_paginate @events
%table
  %thead
    %tr
      %th Name
      %th Start date
      %th End date
      %th Location
      %th Description
      %th
  %tbody
    - @future_events.each do |event|
      %tr
        /%td= event.owner_id
        %td= event.name
        %td= event.start_date.strftime("%d/%m/%Y %H:%M")
        %td= event.end_date.strftime("%d/%m/%Y %H:%M")
        %td= event.location
        %td= event.description
        - if user_signed_in?
          %td= link_to 'S', event, method: :get
          - if event.owner == current_user
            %td= link_to 'E', "/events/#{event.id}/edit"
            %td= link_to 'D', event, method: :delete, data: { confirm: 'Are you sure?' }
/= will_paginate @events
%br         
%h3 Events that took part in
/= will_paginate @events
%table
  %thead
    %tr
      %th Name
      %th Start date
      %th End date
      %th Location
      %th Description
      %th
  %tbody
    - @past_events.each do |event|
      %tr
        %td= event.name
        %td= event.start_date.strftime("%d/%m/%Y %H:%M")
        %td= event.end_date.strftime("%d/%m/%Y %H:%M")
        %td= event.location
        %td= event.description
        - if user_signed_in?
          %td= link_to 'S', event, method: :get
          - if event.owner == current_user
            %td
            %td= link_to 'D', event, method: :delete, data: { confirm: 'Are you sure?' }
/= will_paginate @events
%br
  = link_to "Back", :back

app/views/events/_my_table.html.haml
/= will_paginate @events
%table
  %thead
    %tr
      %th Name
      %th Start date
      %th End date
      %th Location
      %th Description
      %th
  %tbody
    - @events.each do |event|
      - if event.owner == current_user
        %tr
          %td= event.name
          %td= event.start_date.strftime("%d/%m/%Y %H:%M")
          %td= event.end_date.strftime("%d/%m/%Y %H:%M")
          %td= event.location
          %td= event.description
          %td
            = link_to 'S', event, method: :get
          %td
            = link_to 'E', "/events/#{event.id}/edit"
          %td
            = link_to 'D', event, method: :delete, data: { confirm: 'Are you sure?' }
/= will_paginate @events
%br
.inv-butt
  = link_to 'Create a new event', new_event_path
%br
  = link_to "Back", :back

app/views/events/_table.html.haml
/= will_paginate @events
%table
  %thead
    %tr
      %th Name
      %th Start date
      %th End date
      %th Location
      %th Description
      %th
  %tbody
    - @events.each do |event|
      %tr
        %td= event.name
        %td= event.start_date.strftime("%d/%m/%Y %H:%M")
        %td= event.end_date.strftime("%d/%m/%Y %H:%M")
        %td= event.location
        %td= event.description
        - if user_signed_in?
          %td
            = link_to 'S', event, method: :get
          - if event.owner == current_user
            %td
              = link_to 'E', "/events/#{event.id}/edit"
            %td
              = link_to 'D', event, method: :delete, data: { confirm: 'Are you sure?' }
/= will_paginate @events
%br
.inv-butt
  = link_to 'Create a new event', new_event_path

app/views/events/destroy.html.haml
%h1 Events#destroy
%p Find me in app/views/events/destroy.html.haml

app/views/events/edit.html.haml
%h2 Edit #{@event.name.capitalize} event
= form_for(@event) do |f|
  - if @event.errors.any?
    #error_explanation
      %h2
        = pluralize(@event.errors.count, "error")
        prohibited this event from being saved:
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br
    = f.text_field :name
  .field
    = f.label :description
    %br
    = f.text_area :description
  .field
    = f.label :start_date
    %br
    = f.datetime_select :start_date
  .field
    = f.label :end_date
    %br
    = f.datetime_select :end_date
  .field
    = f.label :location
    %br
    = f.text_field :location
    %br
    %br
  .dev-butt
    = f.submit
  %br
.dev-butt
  #{button_to "Delete this event", event_path(@event), data: { confirm: "Are you sure?" }, method: :delete}
%br
  = link_to "Back", :back

app/views/events/index.html.haml
%h1 Listing events
= render partial: 'events/all_table'

app/views/events/my_index.html.haml
%h1 Listing my events
= render partial: 'events/my_table'

app/views/events/new.html.haml
%h2 New event
= form_for(@event, url: events_path(@event.id)) do |f|
  - if @event.errors.any?
    #error_explanation
      %h2
        = pluralize(@event.errors.count, "error")
        prohibited this event from being saved:
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br
    = f.text_field :name
  .field
    = f.label :description
    %br
    = f.text_area :description
  .field
    = f.label :start_date
    %br
    = f.datetime_select :start_date, minute_step: 15
  .field
    = f.label :end_date
    %br
    = f.datetime_select :end_date, minute_step: 15
  .field
    = f.label :location
    %br
    = f.text_field :location
    %br
    %br
    = f.hidden_field :owner_id
  .dev-butt
    = f.submit
%br
  = link_to "Back", :back

app/views/events/show.html.haml
%h1 #{@event.name.capitalize} event
%p
  = @users
%p
  Event name:
  %strong
    = @event.name
%p 
  Start date:
  %strong
    = @event.start_date.strftime("%d/%m/%Y %H:%M")
%p
  End date:
  %strong
    = @event.end_date.strftime("%d/%m/%Y %H:%M")
%p
  Location
  %strong
    = @event.location
%p
  Description:
  %strong
    = @event.description
%p
  Receivers:
  %strong
    - @event_invitations.each do |receiver|
      = receiver.user_email
      ,
%br
-if @event.owner == current_user
  .inv-butt
    = link_to "Edit event", edit_event_path
  %br
  - if @event.start_date >= Time.now
    .inv-butt
      = link_to "Create an invitation to this event", new_invitation_path(event_id: @event.id)
  - else
    .inv-butt
      = link_to 'Delete', @event, method: :delete, data: { confirm: 'Are you sure?' }
%br
  = link_to "Back", :back

app/views/events/update.html.haml
%h1 Events#update
%p Find me in app/views/events/update.html.haml

app/views/home/index.html.haml
.hello-profil
  .row
    .col-xs-2.avatar-image
      = image_tag(current_user.avatar)
    .col-xs-10
      %h1
        Hello #{current_user.first_name} #{current_user.last_name} !
      %p
        How are you today?
= render partial: 'events/f_p_table'
%br
%br
.inv-butt
  = link_to "Create a new event", new_event_path(owner_id: @user.id)

app/views/invitations/create.html.haml
%h1 Invitations#create
%p Find me in app/views/invitations/create.html.haml

app/views/invitations/destroy.html.haml
%h1 Invitations#destroy
%p Find me in app/views/invitations/destroy.html.haml

app/views/invitations/edit.html.haml
%h1 Hello #{@invitation.user_email}!

= form_for(@invitation) do |f|
  .accept-field
    = f.check_box :accepted
    = f.label :accept_invitation
    %br
    %br
  .dev-butt
    = f.submit

app/views/invitations/index.html.haml
%h1 Invitations#index
%p Find me in app/views/invitations/index.html.haml

app/views/invitations/new.html.haml
%h2 New invitation
= form_for @invitation, url: {controller: "invitations", action: "create"} do |f|
  .field
    = text_field_tag 'invitation[user_emails]', @user_emails
  .field
    = f.hidden_field :event_id
    %br
  .dev-butt
    = f.submit "Send emails"
%br
  = link_to "Back", :back

app/views/invitations/show.html.haml
.smiley
  = link_to image_tag("smiley_.png"), root_path

app/views/invitations/update.html.haml
%h1 Invitations#update
%p Find me in app/views/invitations/update.html.haml

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %title InvitorApp
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %link{href: "http://fonts.googleapis.com/css?family=Noto+Sans&subset=latin,latin-ext", rel: "stylesheet", type: "text/css"}
    = csrf_meta_tags
  %body{class: "#{params[:controller]}-#{params[:action]}"}
    .container
      .row#flash
        .col-xs-12
          %p.notice
            #{notice}
          %p.alert
            #{alert}

      .row
        .col-xs-2.col-xs-offset-1.left-menu
          .logo
            = link_to image_tag("logo_.png"), root_path
          .menu
            %ul
              - if current_user
                %li{class: (params[:controller] == 'users' && params[:action] == 'show' ? 'hidden' : '')}
                  = link_to 'My profile', "/users/#{current_user.id}"
                %li{class: (params[:controller] == 'devise/registrations' && params[:action] == 'edit' ? 'hidden' : '')}
                  = link_to 'Edit profile', edit_user_registration_path
                %li{class: (params[:controller] == 'events' && params[:action] == 'index' ? 'hidden' : '')}
                  = link_to 'All events', events_path
                %li{class: (params[:controller] == 'events' && params[:action] == 'my_index' ? 'hidden' : '')}
                  = link_to 'My events', my_events_path
                %hr
                %li
                  = link_to 'Sign out', destroy_user_session_path, method: :delete

              - else
                %li{class: (params[:controller] == 'devise/sessions' && params[:action] == 'new' ? 'hidden' : '')}
                  = link_to 'Sign in', user_session_path
                %li{class: (params[:controller] == 'devise/registrations' && params[:action] == 'new' ? 'hidden' : '')}
                  = link_to 'Registration', new_user_registration_path

        .col-xs-8.col-xs-offset-1
          = yield
      
      .row#footer
        .col-xs-2.col-xs-offset-1.left-menu
          © Invitor_app | 2014

        /   = link_to "Edit profile", '/users/edit'
        /   = link_to "View events", '/events'
        /   = link_to "New invitation", '/invitations/new'
        /   = link_to "My invitations", '/invitations'
        /   = link_to "My balance", '/users/show'
        /   = link_to "Logout", '/sessions/destroy'
        /- else
        /   = render 'home/index'

app/views/layouts/email.html.haml
!!!
%html
  %head
    %meta{:content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}
    %meta{:name => 'viewport', :content => 'width=device-width, initial-scale=1.0'}
  %body
    %table{ style: 'max-width: 500px; background-color: ##f0f0f0;' }
      %tr
        = image_tag 'logo_.png'
      %tr{ style: 'font-family: Noto Sans;' }
        = yield
      %tr
        © Invitor_app | 2014

app/views/users/edit.html.haml
%h3 Edit user profile
= form_for @user, url: {action: 'update'} do |f|
  .field
    = f.label :first_name
    %br
    = f.text_field :first_name
  .field
    = f.label :last_name
    %br
    = f.text_field :last_name
  .field
    = f.label :email
    %br
    = f.email_field :email, autofocus: true
  .field
    = f.label :password
    %br
    = f.password_field :password, autocomplete: "off"
  .field
    = f.label :password_confirmation
    %br
    = f.password_field :password_confirmation, autocomplete: "off"
    %br
    %br
  .dev-butt
    = f.submit "Update"

app/views/users/show.html.haml
.edit-profil
  .row
    .col-xs-2.avatar-image
      %br
      = image_tag(current_user.avatar)
    .col-xs-10
      %p
        First name:
        %strong
          = @user.first_name
      %p
        Last name:
        %strong
          = @user.last_name
      - if @user == current_user
        %p 
          Email:
          %strong
            = @user.email
        %p
          Sign in count:
          %strong
            = @user.sign_in_count
        %p
          Current sign in ip:
          %strong
            = @user.current_sign_in_ip
        %p
          Last sign in ip:
          %strong
            = @user.last_sign_in_ip
%br
.inv-butt
  = link_to "Edit my profil", edit_user_registration_path

app/views/users/update.html.haml
%h1 update